//! General pasteboard (clipboard) access.

use objc2::rc::Retained;
use objc2::runtime::ProtocolObject;
use objc2_app_kit::{
    NSPasteboard, NSPasteboardItem, NSPasteboardType, NSPasteboardTypePNG, NSPasteboardTypeString, NSPasteboardTypeTIFF,
    NSPasteboardWriting,
};
use objc2_foundation::{NSArray, NSData, NSString};

fn general() -> Retained<NSPasteboard> {
    NSPasteboard::generalPasteboard()
}

/// Increments every time anything writes to the clipboard.
pub fn change_count() -> isize {
    general().changeCount()
}

pub fn read_string() -> Option<String> {
    general().stringForType(unsafe { NSPasteboardTypeString }).map(|s| s.to_string())
}

pub fn write_string(text: &str) -> bool {
    let pb = general();
    pb.clearContents();
    let ok = pb.setString_forType(&NSString::from_str(text), unsafe { NSPasteboardTypeString });
    crate::cliphistory::mark_own_change();
    ok
}

/// True when the current clipboard content is marked as a password or other
/// sensitive/transient data (the nspasteboard.org convention password managers use).
pub fn is_sensitive() -> bool {
    const MARKERS: &[&str] = &[
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.1password.1password",
    ];
    general()
        .types()
        .map(|types| types.iter().any(|t| MARKERS.contains(&t.to_string().as_str())))
        .unwrap_or(false)
}

/// Full copy of the clipboard (every item, every type) so it can be put back
/// exactly as it was after we borrow it for a Cmd+C capture.
pub struct Snapshot(Vec<Vec<(Retained<NSPasteboardType>, Retained<NSData>)>>);

pub fn snapshot() -> Snapshot {
    let mut items = Vec::new();
    if let Some(list) = general().pasteboardItems() {
        for item in list.iter() {
            let mut entries = Vec::new();
            for ty in item.types().iter() {
                if let Some(data) = item.dataForType(&ty) {
                    entries.push((ty, data));
                }
            }
            items.push(entries);
        }
    }
    Snapshot(items)
}

pub fn restore(snapshot: Snapshot) {
    crate::cliphistory::suppress_for(std::time::Duration::from_millis(1500));
    let pb = general();
    pb.clearContents();
    if snapshot.0.is_empty() {
        return;
    }
    let items: Vec<Retained<ProtocolObject<dyn NSPasteboardWriting>>> = snapshot
        .0
        .iter()
        .map(|entries| {
            let item = NSPasteboardItem::new();
            for (ty, data) in entries {
                item.setData_forType(data, ty);
            }
            ProtocolObject::from_retained(item)
        })
        .collect();
    pb.writeObjects(&NSArray::from_retained_slice(&items));
}

/// True when the clipboard holds an image (a screenshot or "Copy Image").
pub fn has_image() -> bool {
    let pb = general();
    unsafe { pb.dataForType(NSPasteboardTypePNG).is_some() || pb.dataForType(NSPasteboardTypeTIFF).is_some() }
}

/// The clipboard image as a JPEG data: URL (compact enough to send with an analysis).
pub fn image_data_url() -> Option<String> {
    let pb = general();
    let data = unsafe { pb.dataForType(NSPasteboardTypePNG).or_else(|| pb.dataForType(NSPasteboardTypeTIFF)) }?;
    super::image::jpeg_data_url(&data.to_vec(), 0.82, 4_000_000)
}
